### ISSUE TITLE
can't get right configuration in pod

### ISSUE THREAD

**Issue by like-inspur** [denverdino/lxcfs-initializer#1]
I have test lxcfs on kubernetes 1.8.2. Any configuration of kubernetes or lxcfs creation is right, and even I can see some mounts of pod like this, but when I enter into pod, the cpu and memory are still host's.
      /proc/cpuinfo from lxcfs-proc-cpuinfo (rw)
      /proc/diskstats from lxcfs-proc-diskstats (rw)
      /proc/meminfo from lxcfs-proc-meminfo (rw)
      /proc/stat from lxcfs-proc-stat (rw)

**Comment by pipsqueakup** [comment]
I have a similar issue in 1.9.3, i.e. /proc/meminfo is correct, however /proc/cpuinfo is still host's.

**Comment by virnet** [comment]
我也是，不知道为什么，v1.11.0也不生效

**Comment by virnet** [comment]
1. 启用插件
--enable-admission-plugins=Initializers
2. 启用alpha功能
--runtime-config=admissionregistration.k8s.io/v1alpha1

Two features, Admission Webhooks (beta in 1.9) and Initializers (alpha), address these limitations. They allow admission controllers to be developed out-of-tree and configured at runtime.

**Comment by level077** [comment]
@virnet 不添加这两个参数，都跑不起来。添加之后，看到的还是host的资源，知道怎么回事吗？

**Comment by denverdino** [comment]
Fixed and tested with K8s 1.11

**Comment by zijiwork** [comment]
在kubernetes 1.11.4 上测试， cpu资源仍不能隔离

**Comment by denverdino** [comment]
CPU资源隔离？是什么应用在支持？如果Java建议使用Java 8u191以上版本，lxcfs在https://github.com/lxc/lxcfs/pull/260 已经提供了类似支持，但是还没有release。
