### ISSUE TITLE
Refactoring with PodPreset or Admission Hook

### ISSUE THREAD

**Issue by denverdino** [denverdino/lxcfs-initializer#11]

**Comment by soolaugust** [comment]
@denverdino 
Is there any plan now? as kubernetes v1.14 has removed initializer.

**Comment by denverdino** [comment]
My plan is to do sth with https://github.com/denverdino/admission-webhook-example

**Comment by soolaugust** [comment]
I see, waiting for update. thanks for your work :)

**Comment by denverdino** [comment]
Pls take a look on https://github.com/denverdino/lxcfs-admission-webhook

**Comment by soolaugust** [comment]
I see, thanks :)
