### ISSUE TITLE
/usr/local/lib/lxcfs not exist, causing copy liblxcfs.so to it failed

### ISSUE THREAD

**Issue by liujiong1982** [denverdino/lxcfs-initializer#12]
/usr/local/lib/lxcfs not exist, causing copy liblxcfs.so to it failed

mkdir -p /usr/local/lib/lxcfs /var/lib/lxcfs
need to be done before
cp -f /lxcfs/liblxcfs.so /usr/local/lib/lxcfs/liblxcfs.so

**Comment by denverdino** [comment]
Fixed
