### ISSUE TITLE
lxcfs-daemonset.yaml deployed failed

### ISSUE THREAD

**Issue by databill** [denverdino/lxcfs-initializer#6]
**lxcfs-daemonset.yaml** is deployed failed in a Kubernetes env after the image issue is fixed in https://github.com/denverdino/lxcfs-initializer/pull/5.

The environment information is listed here:

```
[cactus@172-7-11-72 lxcfs-initializer]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

[cactus@172-7-11-72 lxcfs-initializer]$ kubectl -n kube-system get pods
NAME                               READY   STATUS             RESTARTS   AGE
lxcfs-5qq97                        0/1     CrashLoopBackOff   111        9h
lxcfs-925mm                        0/1     CrashLoopBackOff   111        9h
lxcfs-p422z                        0/1     CrashLoopBackOff   111        9h
lxcfs-t47pw                        0/1     CrashLoopBackOff   111        9h

[cactus@172-7-11-72 lxcfs-initializer]$ kubectl -n kube-system log lxcfs-5qq97
lxcfs: error while loading shared libraries: libfuse.so.2: cannot open shared object file: No such file or directory
```

extra information:
 - OS: CentOS Linux release 7.5.1804 (Core)
 - Kernel: 3.10.0-862.14.4.el7.x86_64
 - No lxcfs is installed in the host
 - SELinux: disabled

**Comment by denverdino** [comment]
Hmm, I think it is related to #5, for the Fuse is not enabled in the host

I need some verification on that.

**Comment by databill** [comment]
> Hmm, I think it is related to #5, for the Fuse is not enabled in the host
> 
> I need some verification on that.

I use docker to run the image in host, and I don't find anything in host path `/var/lib/lxcfs` either. 
Something is common with Kubernetes environment and something is different.

There is a issue about lxcfs running in container, refer to https://github.com/lxc/lxcfs/issues/254.

**Comment by denverdino** [comment]
/var/lib/lxcfs is the mount point for lxcfs. You can create the folder or just mount it to container

**Comment by databill** [comment]
> /var/lib/lxcfs is the mount point for lxcfs. You can create the folder or just mount it to container

Yes, actually.
When run the `lxcfs` container, the host directory `/var/lib/lxcfs` will be created if not existed. When the host cannot find anything, it is the same in other containers. 
For example, run an app container to mapping cpuinfo/meminfo in `/var/lib/lxcfs` will case other issues:

```
$ docker run -ti -m 512m -v /var/lib/lxcfs/proc/meminfo:/proc/meminfo --name ubuntu ubuntu /bin/bash

docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: 

starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/lxcfs/proc/meminfo\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/ed5e6a6178052891412ff24b534c7416b4f63a18f88a482876e1b3a6c5ec14cd\\\" at 

\\\"/var/lib/docker/aufs/mnt/ed5e6a6178052891412ff24b534c7416b4f63a18f88a482876e1b3a6c5ec14cd/proc/meminfo\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type.
```

**Comment by denverdino** [comment]
It should be fixed, pls update and try again
