### ISSUE TITLE
nsenter: failed to execute lxcfs: No such file or directory

### ISSUE THREAD

**Issue by duanyifei1937** [denverdino/lxcfs-initializer#8]
when deploy lxcfs-daemonset.yaml, it's faild
log: 
```
nsenter: failed to execute lxcfs: No such file or directory
```

**Comment by qwjhq** [comment]
fix it install lxcfs on physical  , this daemonset manage lxcfs running only . 
see yaml volume mount  section

        volumeMounts:
        - name: cgroup
          mountPath: /sys/fs/cgroup
        - name: lxcfs
          mountPath: /var/lib/lxcfs
          mountPropagation: Bidirectional
        - name: usr-local
          mountPath: /usr/local
      volumes:
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: usr-local
        hostPath:
          path: /usr/local
      - name: lxcfs
        hostPath:
          path: /var/lib/lxcfs
          type: DirectoryOrCreate

**Comment by qwjhq** [comment]
see blog https://blog.51cto.com/bingdian/2356632

**Comment by denverdino** [comment]
Fixed the problem when the /usr/local/bin is not empty, thanks
